### ISSUE TITLE
client_id missing when using client assertion

### ISSUE THREAD

**Issue by thiagolocatelli** [Scalepoint/oauth-token-java-client#1]
Is there a reason as to why client_id is not included in the form params when client assertion is used? I am using an implementation of authorization service that requires client_id as part of the payload when using client assertion.

**Comment by uncleyo** [comment]
The reason is that `client_assertion` authentication method only requires `client_assertion` and `client_assertion_type` parameters according to the specification. The assertion JWT itself already includes `client_id` twice, as `iss` and `sub` claim values.
